#!/usr/bin/env sh

spacebar -m config position                    top
spacebar -m config display                     all
spacebar -m config height                      26
spacebar -m config title                       on
spacebar -m config clock                       on
spacebar -m config spaces                      off
spacebar -m config power                       off
spacebar -m config padding_left                20
spacebar -m config padding_right               20
spacebar -m config spacing_left                25
spacebar -m config spacing_right               15
spacebar -m config text_font                   "Menlo:Regular:13.0"
spacebar -m config background_color            0xffFF
spacebar -m config foreground_color            0xffffffff
spacebar -m config clock_icon_color            0xffffffff
spacebar -m config space_icon_color            0xffffab91
spacebar -m config space_icon_color_secondary  0xff78c4d4
spacebar -m config space_icon_color_tertiary   0xfffff9b0
spacebar -m config spaces_for_all_displays     on
spacebar -m config clock_icon                  
spacebar -m config dnd_icon                    
spacebar -m config clock_format                "%d/%m/%y %R"
# spacebar -m config right_shell                 on
# spacebar -m config right_shell_icon            
# spacebar -m config right_shell_command         "whoami"

echo "spacebar configuration loaded.."
